<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Game.Core\Game.Core.csproj" />
    <ProjectReference Include="..\Game.Imaging\Game.Imaging.csproj" />
    <ProjectReference Include="..\Game.Llm\Game.Llm.csproj" />
    <ProjectReference Include="..\Game.Data\Game.Data.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
